[build]
  command = "npm run build"  
  functions = "functions"   
  publish = "public"       

[build.environment]
  PORT = 8080
  JWT_SECRET_KEY = "AbdulRehman"
  DB_VAR = "mongodb+srv://UsmanAhmadDB:UsmanAhmadDB@cluster0.99d94jp.mongodb.net/ThePetStore"
  STRIPE_SECRET_KEY = "sk_test_51NSCxLIHd297PNDv15uoGJGRLQ8jVLMmAhmzFMDc7Oe6yoKhSRqVdcfq0WF1saBr9ghcf28lRscogXkvnllIsd6T00AzImKNc0"
  AdminEmail = "UsmanDrigrocha+Test@Gmail.com"
  SmtpMail = "rajooadv174@gmail.com"
  SmtpPass = "rrq09876"
